spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ideologicaldomination@gmail.com
    password: WordPass123!
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

server:
  port: 8081